### ISSUE TITLE
Possible typo with Chapter 5 code sample

### ISSUE THREAD

**Issue by daredevil82** [cosmicpython/code#4]
In Chapter 5, a test for [uow](https://github.com/python-leap/code/blob/chapter_05_uow_exercise/tests/integration/test_uow.py#L12-L22) is displayed.  However, it is using list unpacking, and its not obvious whether the difference between `orderlineid` and `id` in 

    [[orderlineid]] = session.execute(
        'SELECT id FROM order_lines WHERE orderid=:orderid AND sku=:sku',
        dict(orderid=orderid, sku=sku)
    )

is deliberate or a typo.  If it is deliberate, it would be helpful to have an explanation of what SQLAlchemy's `orm.session` package is doing to return  the thing referred to with the name `orderlineid`

**Comment by adrienbrunet** [comment]
I had to read it twice and give it a few seconds of thoughts. A footnote should help !

Also for me, it would be a bit less confusing with  

```python
[(orderlineid, )] = ...
```

**Comment by sammiie** [comment]
> In Chapter 5, a test for [uow](https://github.com/python-leap/code/blob/chapter_05_uow_exercise/tests/integration/test_uow.py#L12-L22) is displayed. However, it is using list unpacking, and its not obvious whether the difference between `orderlineid` and `id` in
> 
> ```
> [[orderlineid]] = session.execute(
>     'SELECT id FROM order_lines WHERE orderid=:orderid AND sku=:sku',
>     dict(orderid=orderid, sku=sku)
> )
> ```
> 
> is deliberate or a typo. If it is deliberate, it would be helpful to have an explanation of what SQLAlchemy's `orm.session` package is doing to return the thing referred to with the name `orderlineid`

[[orderlineid]] = session.execute(
    'SELECT id FROM order_lines WHERE orderid=:orderid AND sku=:sku',
    dict(orderid=orderid, sku=sku)
)
session.execute is a method used in SQLAlchemy's ORM to execute raw SQL queries.

The SQL query retrieves the id from the order_lines table based on the orderid and sku provided as parameters.

The result of session.execute is a list of tuples where each tuple contains the values returned by the SQL query.

The [[orderlineid]] syntax is used for list unpacking. It's essentially a way to assign the first element of the first tuple in the result list to the variable orderlineid. This assumes that the SQL query returns a single value, which is commonly the case when you're expecting a single result.

If this is deliberate, it suggests that the SQL query is expected to return a single value (in this case, the id of an order line), and the code is using list unpacking to extract that value from the result.

However, if this is not intentional and the query is supposed to return multiple rows or values, then it could be considered a typo, and the code should be revised accordingly to handle the query results correctly.

To provide more specific guidance or address any concerns about this code, it would be helpful to have additional context or information about the expected behavior of the query and how the result is used in the application.

**Comment by hjwp** [comment]
fixed here, thanks for the feedback everyone. https://github.com/cosmicpython/book/commit/609d5a2303c632012bee7105a6d83eb03f4b708a
