### ISSUE TITLE
Shouldn't `seen` be emptied at some point?

### ISSUE THREAD

**Issue by Florimond** [cosmicpython/code#45]
I just finished chapter 8, and I'm a bit confused that you keep adding to `seen` but I don't see you ever cleaning this set. Wouldn't the commit method be a good place to do that?

https://github.com/cosmicpython/code/blob/69a88f8e05d549cc4cf01a91cd33b0fc4d87014d/src/allocation/service_layer/unit_of_work.py#L26

**Comment by Arseniy-Popov** [comment]
I believe it's fine, because a fresh repository instance, with a empty set of seen products, is initialized each time we `__enter__` a unit of work context, so the set of seen products is never shared between unit of work contexts.
https://github.com/cosmicpython/code/blob/69a88f8e05d549cc4cf01a91cd33b0fc4d87014d/src/allocation/service_layer/unit_of_work.py#L53

**Comment by Florimond** [comment]
@Arseniy-Popov Something I had not realized indeed. I think that answers my question. Thank you.

**Comment by hjwp** [comment]
:+1:  :blush:
